#sfcms_banner_controllers:
##    resource: '../../../src/Controller/'
#    resource: '../../src/Controller/'
#    type: attribute

#aaaaaaaaaaaaaaa_test_route:
#    path: /test
#    controller: Sfcms\BannerBundle\Controller\BannerController::test

#sfcms_banner_routes:
#    resource: '@SfcmsBannerBundle/Controller/'
#    type: annotation

#sfcms_banner_extra_routes:
#    resource: '../../src/Controller/'
#    type: banner_extra_loader


## WORKING DONT TOUCH ##
## WORKING DONT TOUCH ##
## WORKING DONT TOUCH ##
sfcms_banner_routes:
    resource: '../../src/Controller/'
    type: annotation
## WORKING DONT TOUCH ##
## WORKING DONT TOUCH ##
## WORKING DONT TOUCH ##