services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Sfcms\BannerBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    Sfcms\BannerBundle\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

#    Sfcms\BannerBundle\Routing\ExtraLoader:
#        tags: [routing.loader]